[package]
name = "rekordbox-core"
version.workspace = true
edition = "2021"

[dependencies]
binrw.workspace = true
serde.workspace = true
thiserror.workspace = true
xxhash-rust.workspace = true
rusqlite = { version = "0.31", features = ["bundled-sqlcipher-vendored-openssl"] }
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.13"