name: Build yt-dlp-ingest image

on:
  push:
    branches: [main]
    paths:
      - "services/yt-dlp-ingest/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    with:
      service: yt-dlp-ingest
